# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec136283dc0649f0af414654bb2a867586af5e9e2943a6044a90654d24eb4c037ff445a100566f6f83f0abf0dc200d5c1ab357323febd22dc3275a1e8c2adc0

test:
  secret_key_base: 306a9223d7d217d58d4ca38df5e9a2fa31b6b91080a3245a13ac5c69da746c1cd37654b74b834a29b3c0b31ebe9c8f5d9d33831c36e760b49a3701733333abee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
